import {
  AppGlobalState,
  User,
  Project,
  Task,
  ChatChannel,
  ChatMessage,
  DocumentItem,
  InventoryItem,
  InventoryMovement,
  ProductionWorkOrder,
  WorkflowRule,
  AppNotification,
  ComplianceRecord,
  CloudStorageFile,
  SubscriptionState,
  PaymentMethod,
  BillingInvoice,
} from './types';

export const initialUsers: User[] = [
  {
    id: 'usr-1',
    name: 'Sarah Chen, PMP',
    email: 'sarah.chen@omniwork.internal',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    role: 'super_admin',
    department: 'Executive Operations',
    status: 'active',
    lastActive: 'Just now',
  },
  {
    id: 'usr-2',
    name: 'Marcus Vance',
    email: 'm.vance@omniwork.internal',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'project_manager',
    department: 'Engineering & Delivery',
    status: 'active',
    lastActive: '5m ago',
  },
  {
    id: 'usr-3',
    name: 'Dr. Elena Rostova',
    email: 'e.rostova@omniwork.internal',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    role: 'compliance_officer',
    department: 'Legal, HIPAA & GDPR Governance',
    status: 'active',
    lastActive: '12m ago',
  },
  {
    id: 'usr-4',
    name: 'David Kalu',
    email: 'd.kalu@omniwork.internal',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'production_lead',
    department: 'Advanced Manufacturing & Inventory',
    status: 'busy',
    lastActive: '1m ago',
  },
  {
    id: 'usr-5',
    name: 'Aoi Takahashi',
    email: 'a.takahashi@omniwork.internal',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'team_member',
    department: 'Operations & Quality Assurance',
    status: 'away',
    lastActive: '25m ago',
  },
];

export const initialProjects: Project[] = [
  {
    id: 'proj-1',
    name: 'Project Helix: Med-Tech Core System',
    code: 'HLX-2026',
    clientOrDept: 'Healthcare Systems Inc.',
    startDate: '2026-08-01',
    targetDate: '2026-10-15',
    status: 'on_track' as const,
    budget: 185000,
    spent: 114200,
    progress: 74,
    managerId: 'usr-2',
    managerName: 'Marcus Vance',
    description: 'ISO-13485 & HIPAA certified patient monitoring pipeline with real-time sensor streams.',
    tasksCount: 16,
    completedTasksCount: 12,
  },
  {
    id: 'proj-2',
    name: 'Global Inventory Automation v4',
    code: 'INV-GLB',
    clientOrDept: 'Manufacturing Operations',
    startDate: '2026-08-15',
    targetDate: '2026-09-30',
    status: 'at_risk' as const,
    budget: 92000,
    spent: 78500,
    progress: 82,
    managerId: 'usr-4',
    managerName: 'David Kalu',
    description: 'Automating multi-warehouse batch tracking and real-time replenishment triggers.',
    tasksCount: 11,
    completedTasksCount: 8,
  },
  {
    id: 'proj-3',
    name: 'EU GDPR Data Sovereignty Architecture',
    code: 'GDPR-EU',
    clientOrDept: 'Global Compliance Office',
    startDate: '2026-09-01',
    targetDate: '2026-11-20',
    status: 'on_track' as const,
    budget: 65000,
    spent: 24000,
    progress: 45,
    managerId: 'usr-3',
    managerName: 'Dr. Elena Rostova',
    description: 'Automated DSAR fulfillment engine, encryption key rotation, and Article 17 erasure pipelines.',
    tasksCount: 9,
    completedTasksCount: 4,
  },
];

export const initialTasks: Task[] = [
  {
    id: 'task-102',
    title: 'Recalibrate Reorder Triggers for Microcontroller IC-902',
    description: 'Lead-time supplier has shifted from 12 days to 18 days. Update minimum threshold logic to avoid production bottleneck.',
    projectId: 'proj-2',
    projectName: 'Global Inventory Automation v4',
    assigneeId: 'usr-4',
    assigneeName: 'David Kalu',
    assigneeAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    priority: 'high' as const,
    status: 'review' as const,
    dueDate: '2026-09-20',
    estimatedHours: 8,
    loggedHours: 7.5,
    tags: ['Inventory', 'Procurement', 'Critical-Path'],
    subtasks: [
      { id: 'sub-4', title: 'Run Monte Carlo supply simulation', completed: true },
      { id: 'sub-5', title: 'Submit safety stock bump of 500 units to ERP', completed: true },
    ],
    attachments: ['supplier_leadtime_notice.pdf'],
    dependencies: [],
    aiPriorityRank: 1,
    aiPriorityScore: 98,
    aiUrgencyTier: 'critical',
    isBottleneck: true,
    aiSuggestedOrderReason: 'Root critical path blocker: unblocks 2 downstream procurement & assembly tasks; deadline in 48h.',
    createdAt: '2026-09-12T11:00:00Z',
    updatedAt: '2026-09-18T08:15:00Z',
  },
  {
    id: 'task-101',
    title: 'Validate HIPAA PHI Encrypted Data Transit (TLS 1.3)',
    description: 'Verify cryptographic transport layer security for patient telemetric records and ensure zero plaintext payload logs.',
    projectId: 'proj-1',
    projectName: 'Project Helix: Med-Tech Core System',
    assigneeId: 'usr-3',
    assigneeName: 'Dr. Elena Rostova',
    assigneeAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    priority: 'urgent' as const,
    status: 'in_progress' as const,
    dueDate: '2026-09-22',
    estimatedHours: 14,
    loggedHours: 9,
    tags: ['HIPAA', 'Security', 'Cryptographic'],
    subtasks: [
      { id: 'sub-1', title: 'Audit packet payload for unencrypted SSN/identifiers', completed: true },
      { id: 'sub-2', title: 'Confirm HSM key rotation schedule', completed: true },
      { id: 'sub-3', title: 'Generate SHA-256 compliance sign-off receipt', completed: false },
    ],
    attachments: ['hipaa_transit_spec_v2.pdf'],
    hipaaPhiSensitive: true,
    dependencies: [],
    aiPriorityRank: 2,
    aiPriorityScore: 94,
    aiUrgencyTier: 'critical',
    isBottleneck: true,
    aiSuggestedOrderReason: 'Urgent regulatory prerequisite: unblocks penetration testing and enterprise BAA compliance.',
    createdAt: '2026-09-10T09:00:00Z',
    updatedAt: '2026-09-17T14:30:00Z',
  },
  {
    id: 'task-108',
    title: 'Issue Purchase Order PO-2026-118 for 2,500 MCU Units',
    description: 'Procure replenishment batch from secondary certified vendor to safeguard against Q4 semiconductor allocation delays.',
    projectId: 'proj-2',
    projectName: 'Global Inventory Automation v4',
    assigneeId: 'usr-4',
    assigneeName: 'David Kalu',
    assigneeAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    priority: 'urgent' as const,
    status: 'todo' as const,
    dueDate: '2026-09-21',
    estimatedHours: 6,
    loggedHours: 1,
    tags: ['Procurement', 'ERP', 'Budget'],
    subtasks: [
      { id: 'sub-13', title: 'Verify vendor quote against approved budget', completed: true },
      { id: 'sub-14', title: 'Obtain CFO electronic signature', completed: false },
    ],
    attachments: ['po_quote_2026_118.pdf'],
    dependencies: ['task-102'],
    aiPriorityRank: 3,
    aiPriorityScore: 90,
    aiUrgencyTier: 'high',
    isBottleneck: false,
    aiSuggestedOrderReason: 'Immediate follow-up once IC-902 reorder trigger is approved to prevent assembly line shutdown.',
    createdAt: '2026-09-15T09:00:00Z',
    updatedAt: '2026-09-17T11:00:00Z',
  },
  {
    id: 'task-106',
    title: 'Execute End-to-End Penetration Test on Telemetry Ingestion',
    description: 'Black-box vulnerability scan and fuzzer on API Gateway /api/telemetry/stream with OWASP Top 10 vectors.',
    projectId: 'proj-1',
    projectName: 'Project Helix: Med-Tech Core System',
    assigneeId: 'usr-2',
    assigneeName: 'Marcus Vance',
    assigneeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    priority: 'urgent' as const,
    status: 'todo' as const,
    dueDate: '2026-09-24',
    estimatedHours: 16,
    loggedHours: 0,
    tags: ['Security', 'Pen-Test', 'HIPAA'],
    subtasks: [
      { id: 'sub-15', title: 'Simulate man-in-the-middle packet injection', completed: false },
      { id: 'sub-16', title: 'Verify rate limiting on auth endpoints', completed: false },
    ],
    attachments: ['pen_test_scope_doc.pdf'],
    hipaaPhiSensitive: true,
    dependencies: ['task-101'],
    aiPriorityRank: 4,
    aiPriorityScore: 86,
    aiUrgencyTier: 'high',
    isBottleneck: false,
    aiSuggestedOrderReason: 'Awaits TLS 1.3 transit validation. Critical for Project Helix medical release.',
    createdAt: '2026-09-15T14:00:00Z',
    updatedAt: '2026-09-16T16:00:00Z',
  },
  {
    id: 'task-103',
    title: 'Deploy Automated DSAR Portal & Identity Verification',
    description: 'Implement automated self-service Subject Access Request workflow for European Union residents per GDPR regulations.',
    projectId: 'proj-3',
    projectName: 'EU GDPR Data Sovereignty Architecture',
    assigneeId: 'usr-1',
    assigneeName: 'Sarah Chen, PMP',
    assigneeAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    priority: 'high' as const,
    status: 'in_progress' as const,
    dueDate: '2026-09-26',
    estimatedHours: 24,
    loggedHours: 16,
    tags: ['GDPR', 'Compliance', 'Privacy'],
    subtasks: [
      { id: 'sub-6', title: 'Configure dual-factor verification endpoint', completed: true },
      { id: 'sub-7', title: 'Connect automated zip generator for user data dump', completed: false },
      { id: 'sub-8', title: 'Write 30-day statutory countdown timer', completed: true },
    ],
    attachments: ['dsar_flowchart_v4.png'],
    dependencies: [],
    aiPriorityRank: 5,
    aiPriorityScore: 78,
    aiUrgencyTier: 'normal',
    isBottleneck: false,
    aiSuggestedOrderReason: 'Independent high-priority GDPR track; 30-day statutory clock ticking.',
    createdAt: '2026-09-14T08:00:00Z',
    updatedAt: '2026-09-17T18:00:00Z',
  },
  {
    id: 'task-104',
    title: 'Quality Check Batch #MED-8890 Optical Alignment',
    description: 'Inspect first 200 laser collimator units produced on Assembly Line B against sub-micron tolerance boundaries.',
    projectId: 'proj-1',
    projectName: 'Project Helix: Med-Tech Core System',
    assigneeId: 'usr-5',
    assigneeName: 'Aoi Takahashi',
    assigneeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    priority: 'medium' as const,
    status: 'todo' as const,
    dueDate: '2026-09-23',
    estimatedHours: 10,
    loggedHours: 0,
    tags: ['Quality', 'Manufacturing', 'SOP'],
    subtasks: [
      { id: 'sub-9', title: 'Mount test bracket on interferometer', completed: false },
      { id: 'sub-10', title: 'Log optical deviation metrics in QA sheet', completed: false },
    ],
    attachments: [],
    dependencies: ['task-102'],
    aiPriorityRank: 6,
    aiPriorityScore: 72,
    aiUrgencyTier: 'normal',
    isBottleneck: false,
    aiSuggestedOrderReason: 'Scheduled QA inspection for Line B batch run once calibration baseline is fixed.',
    createdAt: '2026-09-16T10:00:00Z',
    updatedAt: '2026-09-16T10:00:00Z',
  },
  {
    id: 'task-109',
    title: 'Release Assembly Work Order WO-2026-092 to Cleanroom Cell A',
    description: 'Initiate physical manufacturing run for 250 units of telemetric bio-sensor arrays.',
    projectId: 'proj-2',
    projectName: 'Global Inventory Automation v4',
    assigneeId: 'usr-4',
    assigneeName: 'David Kalu',
    assigneeAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    priority: 'high' as const,
    status: 'backlog' as const,
    dueDate: '2026-09-28',
    estimatedHours: 32,
    loggedHours: 0,
    tags: ['Manufacturing', 'WorkOrder', 'Cleanroom'],
    subtasks: [
      { id: 'sub-17', title: 'Check cleanroom particulate levels ISO Class 5', completed: false },
      { id: 'sub-18', title: 'Stage component trays in airlock bay', completed: false },
    ],
    attachments: [],
    dependencies: ['task-108', 'task-104'],
    aiPriorityRank: 7,
    aiPriorityScore: 65,
    aiUrgencyTier: 'normal',
    isBottleneck: false,
    aiSuggestedOrderReason: 'Blocked by MCU purchase order receipt and optical QA clearance.',
    createdAt: '2026-09-17T09:00:00Z',
    updatedAt: '2026-09-17T09:00:00Z',
  },
  {
    id: 'task-107',
    title: 'Submit BAA & Compliance Attestation to Healthcare Systems Inc.',
    description: 'Deliver signed Business Associate Agreement, SOC 2 Type II summary, and pen-test remediation certificate.',
    projectId: 'proj-1',
    projectName: 'Project Helix: Med-Tech Core System',
    assigneeId: 'usr-3',
    assigneeName: 'Dr. Elena Rostova',
    assigneeAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    priority: 'high' as const,
    status: 'backlog' as const,
    dueDate: '2026-09-30',
    estimatedHours: 8,
    loggedHours: 2,
    tags: ['Legal', 'BAA', 'Compliance'],
    subtasks: [
      { id: 'sub-19', title: 'Compile encryption audit logs', completed: false },
      { id: 'sub-20', title: 'Attach pen-test signoff document', completed: false },
    ],
    attachments: ['baa_template_draft.pdf'],
    dependencies: ['task-101', 'task-106'],
    aiPriorityRank: 8,
    aiPriorityScore: 58,
    aiUrgencyTier: 'low',
    isBottleneck: false,
    aiSuggestedOrderReason: 'Final contractual milestone; unblocked upon penetration test completion.',
    createdAt: '2026-09-17T11:00:00Z',
    updatedAt: '2026-09-17T11:00:00Z',
  },
  {
    id: 'task-105',
    title: 'Audit Multi-Region Cloud Storage Bucket Permissions',
    description: 'Ensure all AWS S3 and GCS buckets enforce server-side SSE-KMS / AES-256 and public ACL block.',
    projectId: 'proj-3',
    projectName: 'EU GDPR Data Sovereignty Architecture',
    assigneeId: 'usr-2',
    assigneeName: 'Marcus Vance',
    assigneeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    priority: 'medium' as const,
    status: 'done' as const,
    dueDate: '2026-09-16',
    estimatedHours: 12,
    loggedHours: 11,
    tags: ['Cloud', 'DevOps', 'Security'],
    subtasks: [
      { id: 'sub-11', title: 'Scan S3 bucket policies via CloudTrail', completed: true },
      { id: 'sub-12', title: 'Verify KMS key alias rotation', completed: true },
    ],
    attachments: ['cloud_security_audit_report.json'],
    dependencies: [],
    aiPriorityRank: 99,
    aiPriorityScore: 0,
    aiUrgencyTier: 'low',
    isBottleneck: false,
    aiSuggestedOrderReason: 'Task completed and verified in audit log.',
    createdAt: '2026-09-08T09:30:00Z',
    updatedAt: '2026-09-16T17:00:00Z',
  },
];

export interface ExampleScenario {
  id: string;
  name: string;
  description: string;
  badge: string;
  tasks: Task[];
}

export const exampleTaskScenarios: ExampleScenario[] = [
  {
    id: 'scenario-critical-path',
    name: 'Critical Path & Blocker Resolution (Default)',
    description: 'Complex multi-team dependencies across med-tech hardware, inventory triggers & HIPAA transit security.',
    badge: 'Standard Workstream',
    tasks: initialTasks,
  },
  {
    id: 'scenario-supply-crisis',
    name: 'Semiconductor Supply Shock Emergency',
    description: 'Supplier lead times triple overnight. Prioritizes emergency component re-sourcing and re-allocating cleanroom work orders.',
    badge: 'Supply Chain Alert',
    tasks: [
      {
        id: 'task-s1',
        title: 'Emergency Dual-Source RFQ for Microcontrollers (Lead Time Crisis)',
        description: 'Vendor A notified a 6-week delay. Issue immediate RFQ to secondary certified European distributor.',
        projectId: 'proj-2',
        projectName: 'Global Inventory Automation v4',
        assigneeId: 'usr-4',
        assigneeName: 'David Kalu',
        assigneeAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        priority: 'urgent',
        status: 'in_progress',
        dueDate: '2026-09-19',
        estimatedHours: 6,
        loggedHours: 4,
        tags: ['SupplyChain', 'Urgent', 'Procurement'],
        subtasks: [
          { id: 'sub-s1', title: 'Evaluate distributor component authenticity certificates', completed: true },
          { id: 'sub-s2', title: 'Lock pricing for 5,000 units buffer inventory', completed: false },
        ],
        attachments: [],
        dependencies: [],
        aiPriorityRank: 1,
        aiPriorityScore: 99,
        aiUrgencyTier: 'critical',
        isBottleneck: true,
        aiSuggestedOrderReason: 'CRITICAL BOTTLENECK: Blocks entire production facility; deadline in 24h.',
        createdAt: '2026-09-18T06:00:00Z',
        updatedAt: '2026-09-18T08:00:00Z',
      },
      {
        id: 'task-s2',
        title: 'Re-sequence Cleanroom Work Orders to Mechanical Assembly',
        description: 'Shift production cells from electronic PCB mounting to mechanical enclosure fabrication while waiting on silicon.',
        projectId: 'proj-2',
        projectName: 'Global Inventory Automation v4',
        assigneeId: 'usr-5',
        assigneeName: 'Aoi Takahashi',
        assigneeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        priority: 'high',
        status: 'todo',
        dueDate: '2026-09-20',
        estimatedHours: 8,
        loggedHours: 0,
        tags: ['Manufacturing', 'Assembly', 'LineBalance'],
        subtasks: [
          { id: 'sub-s3', title: 'Retool automated pick-and-place gantry', completed: false },
          { id: 'sub-s4', title: 'Brief night shift supervisor on enclosure specs', completed: false },
        ],
        attachments: [],
        dependencies: ['task-s1'],
        aiPriorityRank: 2,
        aiPriorityScore: 92,
        aiUrgencyTier: 'high',
        isBottleneck: false,
        aiSuggestedOrderReason: 'Prevents $45k/day cleanroom idle cost once alternate component allocation is locked.',
        createdAt: '2026-09-18T07:00:00Z',
        updatedAt: '2026-09-18T07:00:00Z',
      },
      {
        id: 'task-s3',
        title: 'Customer Delivery Milestone Rescheduling & SLA Notice',
        description: 'Prepare transparent delivery window adjustment notification for Healthcare Systems Inc.',
        projectId: 'proj-1',
        projectName: 'Project Helix: Med-Tech Core System',
        assigneeId: 'usr-1',
        assigneeName: 'Sarah Chen, PMP',
        assigneeAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
        priority: 'high',
        status: 'todo',
        dueDate: '2026-09-21',
        estimatedHours: 4,
        loggedHours: 0,
        tags: ['ClientComm', 'SLA', 'Executive'],
        subtasks: [
          { id: 'sub-s5', title: 'Review penalty clauses in master services agreement', completed: false },
          { id: 'sub-s6', title: 'Schedule stakeholder briefing call', completed: false },
        ],
        attachments: [],
        dependencies: ['task-s1', 'task-s2'],
        aiPriorityRank: 3,
        aiPriorityScore: 84,
        aiUrgencyTier: 'high',
        isBottleneck: false,
        aiSuggestedOrderReason: 'Stakeholder communication must be grounded in verified alternate delivery date.',
        createdAt: '2026-09-18T07:30:00Z',
        updatedAt: '2026-09-18T07:30:00Z',
      },
    ],
  },
  {
    id: 'scenario-hipaa-audit',
    name: 'HIPAA & GDPR Annual Certification Sprint',
    description: 'Full compliance enforcement sprint ahead of external third-party BAA and privacy audit.',
    badge: 'Regulatory Audit',
    tasks: [
      {
        id: 'task-h1',
        title: 'Revoke Inactive SSH & Cloud IAM Keys Older Than 90 Days',
        description: 'Mandatory HIPAA Security Rule §164.312 access control compliance check.',
        projectId: 'proj-3',
        projectName: 'EU GDPR Data Sovereignty Architecture',
        assigneeId: 'usr-2',
        assigneeName: 'Marcus Vance',
        assigneeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        priority: 'urgent',
        status: 'in_progress',
        dueDate: '2026-09-19',
        estimatedHours: 5,
        loggedHours: 3,
        tags: ['Security', 'IAM', 'HIPAA'],
        subtasks: [
          { id: 'sub-h1', title: 'Query AWS IAM credential report for >90d keys', completed: true },
          { id: 'sub-h2', title: 'Revoke and rotate service account tokens', completed: false },
        ],
        attachments: [],
        dependencies: [],
        aiPriorityRank: 1,
        aiPriorityScore: 97,
        aiUrgencyTier: 'critical',
        isBottleneck: true,
        aiSuggestedOrderReason: 'Immediate regulatory requirement: zero tolerance for stale administrative credentials.',
        createdAt: '2026-09-18T06:30:00Z',
        updatedAt: '2026-09-18T08:00:00Z',
      },
      {
        id: 'task-h2',
        title: 'Audit ePHI Database Query Logs for Break-Glass Usage',
        description: 'Verify all emergency override access logs have verified clinician justification recorded in tamper-proof audit trail.',
        projectId: 'proj-1',
        projectName: 'Project Helix: Med-Tech Core System',
        assigneeId: 'usr-3',
        assigneeName: 'Dr. Elena Rostova',
        assigneeAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
        priority: 'urgent',
        status: 'todo',
        dueDate: '2026-09-20',
        estimatedHours: 8,
        loggedHours: 0,
        tags: ['HIPAA', 'Audit', 'Governance'],
        subtasks: [
          { id: 'sub-h3', title: 'Cross-reference emergency override events with on-call roster', completed: false },
          { id: 'sub-h4', title: 'Sign cryptographic audit hash block', completed: false },
        ],
        attachments: [],
        dependencies: ['task-h1'],
        aiPriorityRank: 2,
        aiPriorityScore: 91,
        aiUrgencyTier: 'high',
        isBottleneck: false,
        aiSuggestedOrderReason: 'Unblocks lead auditor verification of Section 164.312(a)(2)(ii) safeguards.',
        createdAt: '2026-09-18T07:00:00Z',
        updatedAt: '2026-09-18T07:00:00Z',
      },
      {
        id: 'task-h3',
        title: 'Publish Annual GDPR Transparency & DSAR Metrics Report',
        description: 'Generate Article 15/17 compliance statistics for legal team review and public filing.',
        projectId: 'proj-3',
        projectName: 'EU GDPR Data Sovereignty Architecture',
        assigneeId: 'usr-1',
        assigneeName: 'Sarah Chen, PMP',
        assigneeAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
        priority: 'high',
        status: 'todo',
        dueDate: '2026-09-22',
        estimatedHours: 12,
        loggedHours: 0,
        tags: ['GDPR', 'Legal', 'Reporting'],
        subtasks: [
          { id: 'sub-h5', title: 'Compile average DSAR resolution turnaround (current: 4.2 days)', completed: false },
          { id: 'sub-h6', title: 'Export cryptographic proof manifests', completed: false },
        ],
        attachments: [],
        dependencies: ['task-h2'],
        aiPriorityRank: 3,
        aiPriorityScore: 82,
        aiUrgencyTier: 'normal',
        isBottleneck: false,
        aiSuggestedOrderReason: 'Legal filing ready once break-glass audit logs are validated.',
        createdAt: '2026-09-18T07:30:00Z',
        updatedAt: '2026-09-18T07:30:00Z',
      },
    ],
  },
];

export const initialChannels: ChatChannel[] = [
  {
    id: 'chan-general',
    name: 'general',
    description: 'Company-wide updates, standups, and general office chatter.',
    isPrivate: false,
    members: ['usr-1', 'usr-2', 'usr-3', 'usr-4', 'usr-5'],
    topic: 'Company All-Hands Scheduled for Friday 10:00 AM PST',
    category: 'team' as const,
  },
  {
    id: 'chan-ops',
    name: 'operations-and-projects',
    description: 'Sprint planning, project milestones, and cross-functional deliverables.',
    isPrivate: false,
    members: ['usr-1', 'usr-2', 'usr-4'],
    topic: 'Sprint 34: Project Helix & Inventory Automation Milestones',
    category: 'project' as const,
  },
  {
    id: 'chan-inventory',
    name: 'production-and-inventory',
    description: 'Real-time warehouse movements, work orders, and reorder alerts.',
    isPrivate: false,
    members: ['usr-1', 'usr-4', 'usr-5'],
    topic: 'Assembly Line B schedule & supplier lead times',
    category: 'operations' as const,
  },
  {
    id: 'chan-compliance',
    name: 'hipaa-gdpr-governance',
    description: 'Restricted channel for compliance officers, legal reviews, and privacy audits.',
    isPrivate: true,
    members: ['usr-1', 'usr-3'],
    topic: 'Confidential: GDPR Article 17 audits & HIPAA PHI security sign-offs',
    category: 'compliance' as const,
  },
];

export const initialMessages: ChatMessage[] = [
  {
    id: 'msg-1',
    channelId: 'chan-general',
    senderId: 'usr-1',
    senderName: 'Sarah Chen, PMP',
    senderAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    senderRole: 'super_admin' as const,
    content: 'Welcome everyone to the upgraded OmniWork Enterprise Suite! All task deadlines, production inventory movements, and HIPAA/GDPR audit records are now unified with live cross-platform synchronization.',
    timestamp: '2026-09-18T08:00:00Z',
    reactions: [{ emoji: '🚀', users: ['usr-2', 'usr-3', 'usr-4'] }, { emoji: '🙌', users: ['usr-5'] }],
  },
  {
    id: 'msg-2',
    channelId: 'chan-inventory',
    senderId: 'usr-4',
    senderName: 'David Kalu',
    senderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    senderRole: 'production_lead' as const,
    content: 'Alert team: Microcontroller IC-902 stock dropped to 380 units. Automated reorder workflow has flagged an urgent replenishment recommendation.',
    timestamp: '2026-09-18T08:15:00Z',
    reactions: [{ emoji: '👀', users: ['usr-1'] }],
  },
  {
    id: 'msg-3',
    channelId: 'chan-compliance',
    senderId: 'usr-3',
    senderName: 'Dr. Elena Rostova',
    senderAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    senderRole: 'compliance_officer' as const,
    content: 'I have verified that all patient telemetry documents and cloud files in Project Helix carry AES-256-GCM encryption with immutable SHA-256 audit logging.',
    timestamp: '2026-09-18T08:30:00Z',
    reactions: [{ emoji: '🛡️', users: ['usr-1', 'usr-2'] }],
  },
];

export const initialDocuments: DocumentItem[] = [
  {
    id: 'doc-1',
    title: 'SOP-204: Production Line QA and Micro-Tolerance Calibration',
    category: 'SOP' as const,
    content: `# SOP-204: Production Line QA and Micro-Tolerance Calibration\n\n**Standard Operating Procedure**\n*Department: Advanced Manufacturing & Quality Engineering*\n\n## 1. Purpose\nThis protocol establishes mandatory inspection boundaries for laser collimators and optoelectronic modules in medical diagnostics.\n\n## 2. Equipment Required\n1. Optical Interferometer (Class 4 Calibrated)\n2. Anti-static cleanroom matting (ISO Class 5)\n3. Automated Torque Driver (0.42 Nm ± 0.02 Nm)\n\n## 3. Workflow Steps\n- Step A: Verify raw materials against Batch/Lot certificate.\n- Step B: Align collimator barrel inside optical jig.\n- Step C: Transmit continuous beam and verify deviation is < 0.25 arcseconds.\n- Step D: Sign off QA passport and seal inside nitrogen-purged ESD barrier pouch.`,
    authorId: 'usr-4',
    authorName: 'David Kalu',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    lastModified: '2026-09-17T15:45:00Z',
    version: 3,
    versions: [
      { version: 1, timestamp: '2026-08-10T10:00:00Z', authorName: 'David Kalu', summary: 'Initial SOP creation', contentSnippet: 'Initial procedure draft' },
      { version: 2, timestamp: '2026-08-25T14:30:00Z', authorName: 'Aoi Takahashi', summary: 'Updated torque values', contentSnippet: 'Torque specification 0.40 -> 0.42 Nm' },
      { version: 3, timestamp: '2026-09-17T15:45:00Z', authorName: 'David Kalu', summary: 'Added nitrogen purge requirement', contentSnippet: 'Added ESD barrier pouch sealing protocol' },
    ],
    permissions: [
      { role: 'super_admin' as const, access: 'admin' as const },
      { role: 'production_lead' as const, access: 'edit' as const },
      { role: 'project_manager' as const, access: 'edit' as const },
      { role: 'team_member' as const, access: 'view' as const },
    ],
    isEncrypted: true,
    phiFlag: false,
    tags: ['Manufacturing', 'ISO-13485', 'Cleanroom'],
  },
  {
    id: 'doc-2',
    title: 'HIPAA-SEC-01: Protected Health Information Safeguards Policy',
    category: 'Compliance' as const,
    content: `# HIPAA-SEC-01: Protected Health Information Safeguards Policy\n\n**Compliance Classification: STRICT CONFIDENTIAL**\n*Audited by Legal & Data Governance*\n\n## Section 1: Access Controls & RBAC Enforcement\nAccess to electronic Protected Health Information (ePHI) is strictly granted on a minimum-necessary principle according to defined roles (45 CFR § 164.312(a)(1)).\n\n## Section 2: Encryption at Rest & In Transit\n- All persistent databases utilize AES-256-GCM column-level encryption.\n- Network transmissions require TLS 1.3 with forward secrecy ciphers.\n\n## Section 3: Tamper-Evident Audit Logging\nEvery query, export, or administrative touch on patient records writes a cryptographic digest containing timestamp, operator ID, and SHA-256 signature to the compliance vault.`,
    authorId: 'usr-3',
    authorName: 'Dr. Elena Rostova',
    authorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    lastModified: '2026-09-18T07:15:00Z',
    version: 5,
    versions: [
      { version: 4, timestamp: '2026-09-02T11:00:00Z', authorName: 'Dr. Elena Rostova', summary: 'Annual HIPAA audit revision', contentSnippet: 'Updated CFR citation references' },
      { version: 5, timestamp: '2026-09-18T07:15:00Z', authorName: 'Dr. Elena Rostova', summary: 'Mandated TLS 1.3 minimum standard', contentSnippet: 'Enforced TLS 1.3 for all microservices' },
    ],
    permissions: [
      { role: 'super_admin' as const, access: 'admin' as const },
      { role: 'compliance_officer' as const, access: 'admin' as const },
      { role: 'project_manager' as const, access: 'view' as const },
    ],
    isEncrypted: true,
    phiFlag: true,
    tags: ['HIPAA', 'ePHI', 'Legal', 'Security'],
  },
];

export const initialInventory: InventoryItem[] = [
  {
    id: 'inv-1',
    sku: 'MCU-902-EXT',
    name: 'Microcontroller IC-902 (Automotive Grade)',
    category: 'Semiconductors',
    quantity: 380,
    unit: 'pcs',
    minThreshold: 500,
    reorderQuantity: 1200,
    unitCost: 14.85,
    warehouseLocation: 'Bay 3 - Bin A-14',
    batchNumber: 'LOT-2026-8841',
    expirationDate: '2028-12-31',
    status: 'low_stock' as const,
    lastAudited: '2026-09-15',
    supplierName: 'Silicon Dynamics Global Ltd.',
  },
  {
    id: 'inv-2',
    sku: 'SEN-OPT-55',
    name: 'Biometric Optical Sensor Array v3',
    category: 'Medical Sensors',
    quantity: 1420,
    unit: 'units',
    minThreshold: 400,
    reorderQuantity: 800,
    unitCost: 32.50,
    warehouseLocation: 'Bay 1 - Vault Cleanroom',
    batchNumber: 'LOT-2026-9012',
    expirationDate: '2027-06-30',
    status: 'in_stock' as const,
    lastAudited: '2026-09-17',
    supplierName: 'Photonics BioTech AG',
  },
  {
    id: 'inv-3',
    sku: 'MOT-SRV-24V',
    name: 'Precision Micro-Stepper Motor 24V',
    category: 'Actuators',
    quantity: 860,
    unit: 'units',
    minThreshold: 300,
    reorderQuantity: 600,
    unitCost: 21.00,
    warehouseLocation: 'Bay 2 - Bin C-02',
    batchNumber: 'LOT-2026-7734',
    status: 'in_stock' as const,
    lastAudited: '2026-09-12',
    supplierName: 'Nippon Micro-Motion Corp.',
  },
  {
    id: 'inv-4',
    sku: 'BAT-LPO-48V',
    name: 'Lithium Polymer Ultra-Pack 48V 10Ah',
    category: 'Power Modules',
    quantity: 125,
    unit: 'packs',
    minThreshold: 150,
    reorderQuantity: 300,
    unitCost: 110.00,
    warehouseLocation: 'Bay 4 - Hazardous Storage',
    batchNumber: 'LOT-2026-6621',
    expirationDate: '2027-10-15',
    status: 'low_stock' as const,
    lastAudited: '2026-09-14',
    supplierName: 'VoltCore Energy Solutions',
  },
  {
    id: 'inv-5',
    sku: 'CAS-ALU-6061',
    name: 'CNC Milled Aluminum 6061 Protective Casing',
    category: 'Mechanical Enclosures',
    quantity: 2100,
    unit: 'pcs',
    minThreshold: 500,
    reorderQuantity: 1500,
    unitCost: 8.40,
    warehouseLocation: 'Bay 5 - Rack F-08',
    batchNumber: 'LOT-2026-4491',
    status: 'in_stock' as const,
    lastAudited: '2026-09-10',
    supplierName: 'Apex Precision Metals',
  },
];

export const initialInventoryMovements: InventoryMovement[] = [
  {
    id: 'mov-1',
    itemId: 'inv-1',
    itemName: 'Microcontroller IC-902 (Automotive Grade)',
    sku: 'MCU-902-EXT',
    type: 'stock_out' as const,
    quantity: 120,
    previousQuantity: 500,
    newQuantity: 380,
    referenceOrder: 'WO-2026-091',
    performedBy: 'David Kalu',
    timestamp: '2026-09-18T08:10:00Z',
    notes: 'Allocated to Work Order WO-2026-091 (Production Line B).',
  },
  {
    id: 'mov-2',
    itemId: 'inv-2',
    itemName: 'Biometric Optical Sensor Array v3',
    sku: 'SEN-OPT-55',
    type: 'stock_in' as const,
    quantity: 500,
    previousQuantity: 920,
    newQuantity: 1420,
    referenceOrder: 'PO-2026-4412',
    performedBy: 'Aoi Takahashi',
    timestamp: '2026-09-17T14:20:00Z',
    notes: 'Incoming shipment received, QA certificate confirmed clean.',
  },
];

export const initialWorkOrders: ProductionWorkOrder[] = [
  {
    id: 'wo-1',
    orderNumber: 'WO-2026-091',
    title: 'Batch Run: Med-Tech Patient Vitals Hub',
    targetQuantity: 100,
    completedQuantity: 65,
    currentStage: 'in_production' as const,
    priority: 'rush' as const,
    assignedTeam: 'Assembly Cell Alpha',
    deadline: '2026-09-22',
    sku: 'MCU-902-EXT',
    startDate: '2026-09-15',
    notes: 'Priority delivery for hospital clinical trial deployment.',
    batchLotNumber: 'LOT-2026-8841',
  },
  {
    id: 'wo-2',
    orderNumber: 'WO-2026-092',
    title: 'Optical Sensor Calibration & Packaging',
    targetQuantity: 250,
    completedQuantity: 250,
    currentStage: 'quality_check' as const,
    priority: 'normal' as const,
    assignedTeam: 'QA Inspection Cell 2',
    deadline: '2026-09-24',
    sku: 'SEN-OPT-55',
    startDate: '2026-09-16',
    notes: 'Final zero-defect verification before warehouse release.',
    batchLotNumber: 'LOT-2026-9012',
  },
  {
    id: 'wo-3',
    orderNumber: 'WO-2026-093',
    title: 'Sub-Assembly: Micro-Stepper Actuator Modules',
    targetQuantity: 400,
    completedQuantity: 0,
    currentStage: 'material_allocation' as const,
    priority: 'normal' as const,
    assignedTeam: 'Line C Robotics',
    deadline: '2026-09-29',
    sku: 'MOT-SRV-24V',
    startDate: '2026-09-19',
    notes: 'Pending final fastener delivery from warehouse Bay 2.',
    batchLotNumber: 'LOT-2026-7734',
  },
];

export const initialWorkflows: WorkflowRule[] = [
  {
    id: 'wf-1',
    name: 'Urgent Inventory Stock Reorder Alert',
    description: 'When any SKU quantity drops below minThreshold, auto-generate purchase order proposal and send push notification.',
    trigger: 'inventory_low_stock' as const,
    conditionDescription: 'Stock level < Minimum Safety Threshold',
    actionType: 'send_push_notification' as const,
    targetChannelId: 'chan-inventory',
    active: true,
    triggerCount: 14,
    lastTriggered: '2026-09-18T08:12:00Z',
  },
  {
    id: 'wf-2',
    name: 'Task Status "In Review" Manager Notification',
    description: 'When any critical or urgent task moves to "review", notify Project Manager immediately.',
    trigger: 'task_status_change' as const,
    conditionDescription: 'Status changes to "review" and Priority is Urgent/High',
    actionType: 'notify_channel' as const,
    targetChannelId: 'chan-ops',
    active: true,
    triggerCount: 38,
    lastTriggered: '2026-09-18T08:15:00Z',
  },
  {
    id: 'wf-3',
    name: 'HIPAA ePHI Access Cryptographic Log & Alert',
    description: 'When documents tagged with HIPAA/PHI are viewed or downloaded, log immutable audit record and dispatch verification alert.',
    trigger: 'phi_data_access' as const,
    conditionDescription: 'File/Document flagged with phiFlag == true accessed',
    actionType: 'log_audit' as const,
    targetChannelId: 'chan-compliance',
    active: true,
    triggerCount: 22,
    lastTriggered: '2026-09-18T08:30:00Z',
  },
  {
    id: 'wf-4',
    name: '48h Deadline Proximity Web Push',
    description: 'Send automated reminder push notifications when project milestone deadline is under 48 hours.',
    trigger: 'approaching_deadline' as const,
    conditionDescription: 'Target date - Current date <= 48 hours',
    actionType: 'send_push_notification' as const,
    active: true,
    triggerCount: 9,
    lastTriggered: '2026-09-17T18:00:00Z',
  },
];

export const initialNotifications: AppNotification[] = [
  {
    id: 'notif-1',
    title: 'Low Stock Alert: Microcontroller IC-902',
    message: 'Current stock is 380 pcs (Threshold: 500 pcs). Automated replenishment request proposed.',
    type: 'inventory' as const,
    timestamp: '2026-09-18T08:12:00Z',
    read: false,
    linkTab: 'inventory',
    actionRequired: true,
  },
  {
    id: 'notif-2',
    title: 'Task Moved to Review',
    message: 'David Kalu submitted "Recalibrate Reorder Triggers" for Project Manager review.',
    type: 'workflow' as const,
    timestamp: '2026-09-18T08:15:00Z',
    read: false,
    linkTab: 'tasks',
  },
  {
    id: 'notif-3',
    title: 'Approaching Project Deadline',
    message: 'Global Inventory Automation v4 milestone due in 12 days. 3 high-priority tasks remaining.',
    type: 'deadline' as const,
    timestamp: '2026-09-18T07:45:00Z',
    read: true,
    linkTab: 'tasks',
  },
  {
    id: 'notif-4',
    title: 'HIPAA Integrity Check Passed',
    message: 'Monthly automated cryptographic digest verification completed with 100% hash integrity.',
    type: 'compliance' as const,
    timestamp: '2026-09-17T22:00:00Z',
    read: true,
    linkTab: 'compliance',
  },
];

export const initialComplianceRecords: ComplianceRecord[] = [
  {
    id: 'cmp-1',
    standard: 'GDPR' as const,
    type: 'DSAR_REQUEST' as const,
    subject: 'DSAR-EU-2026-042 (Citizen: Hans Mueller)',
    operator: 'Dr. Elena Rostova',
    operatorRole: 'compliance_officer',
    status: 'verified' as const,
    timestamp: '2026-09-18T06:30:00Z',
    hashSignature: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    details: 'Data Subject Access Request received and identity confirmed via eIDAS Level 2. User data bundle compiled with zero leak.',
  },
  {
    id: 'cmp-2',
    standard: 'HIPAA' as const,
    type: 'PHI_ACCESS' as const,
    subject: 'Patient Telemetry Data Stream Access (Project Helix)',
    operator: 'Sarah Chen, PMP',
    operatorRole: 'super_admin',
    status: 'verified' as const,
    timestamp: '2026-09-18T08:30:00Z',
    hashSignature: '8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4',
    details: 'Authorized access to anonymized test sensor telemetry for clinical protocol validation. All identifiable tags masked.',
  },
  {
    id: 'cmp-3',
    standard: 'GDPR' as const,
    type: 'RIGHT_TO_ERASURE' as const,
    subject: 'Article 17 Erasure (Case ID: ERA-8812)',
    operator: 'Dr. Elena Rostova',
    operatorRole: 'compliance_officer',
    status: 'resolved' as const,
    timestamp: '2026-09-16T14:10:00Z',
    hashSignature: '4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b',
    details: 'Completed permanent cryptographic purge of expired applicant records across production and replica databases.',
  },
  {
    id: 'cmp-4',
    standard: 'HIPAA' as const,
    type: 'BAA_AUDIT' as const,
    subject: 'Annual Business Associate Agreement (Cloud Infrastructure Provider)',
    operator: 'Dr. Elena Rostova',
    operatorRole: 'compliance_officer',
    status: 'verified' as const,
    timestamp: '2026-09-15T11:00:00Z',
    hashSignature: 'd4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35',
    details: 'Executed BAA countersignature affirming HITECH Omnibus rule compliance and 24-hour breach notification SLA.',
  },
];

export const initialCloudFiles: CloudStorageFile[] = [
  {
    id: 'cld-1',
    fileName: 'Helix_Clinical_Trial_Protocol_v4.pdf',
    fileSize: '14.2 MB',
    mimeType: 'application/pdf',
    cloudProvider: 'AWS S3' as const,
    encryption: 'AES-256-GCM' as const,
    uploadDate: '2026-09-16',
    uploadedBy: 'Dr. Elena Rostova',
    checksum: 'sha256:7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069',
    accessLevel: 'Restricted PHI' as const,
  },
  {
    id: 'cld-2',
    fileName: 'Global_Inventory_Valuation_Q3_2026.xlsx',
    fileSize: '4.8 MB',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    cloudProvider: 'Google Cloud Storage' as const,
    encryption: 'AES-256-GCM' as const,
    uploadDate: '2026-09-17',
    uploadedBy: 'David Kalu',
    checksum: 'sha256:c2827eb4d7093554ef8c865a03ad3417b6de57f13d7b511327e3e431d99f8388',
    accessLevel: 'Confidential' as const,
  },
  {
    id: 'cld-3',
    fileName: 'ISO_13485_Quality_Manual_Audit_Signoff.pdf',
    fileSize: '8.1 MB',
    mimeType: 'application/pdf',
    cloudProvider: 'Azure Blob' as const,
    encryption: 'AES-256-GCM' as const,
    uploadDate: '2026-09-14',
    uploadedBy: 'Sarah Chen, PMP',
    checksum: 'sha256:ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad',
    accessLevel: 'Internal' as const,
  },
];

export const initialSubscription: SubscriptionState = {
  currentPlan: 'professional',
  billingInterval: 'monthly',
  seatsAllocated: 25,
  seatsUsed: 5,
  nextBillingDate: '2026-10-01',
  autoRenew: true,
  storageUsedGb: 42.8,
  storageLimitGb: 100,
  paymentMethods: [
    {
      id: 'pm-1',
      type: 'credit_card',
      isDefault: true,
      name: 'Sarah Chen',
      last4: '4242',
      brand: 'visa',
      expiryMonth: 12,
      expiryYear: 2028,
      billingEmail: 'sarah.chen@omniwork.internal',
      postalCode: '94107',
      country: 'United States',
      createdAt: '2026-01-15T10:00:00Z',
    },
    {
      id: 'pm-2',
      type: 'credit_card',
      isDefault: false,
      name: 'OmniWork Operations Purchasing',
      last4: '8831',
      brand: 'mastercard',
      expiryMonth: 8,
      expiryYear: 2029,
      billingEmail: 'procurement@omniwork.internal',
      postalCode: '94107',
      country: 'United States',
      createdAt: '2026-03-22T14:30:00Z',
    },
    {
      id: 'pm-3',
      type: 'bank_ach',
      isDefault: false,
      name: 'OmniWork Technologies LLC',
      last4: '6019',
      brand: 'ach',
      bankName: 'JPMorgan Chase Commercial',
      accountType: 'corporate',
      billingEmail: 'treasury@omniwork.internal',
      createdAt: '2026-05-10T09:15:00Z',
    },
  ],
  invoices: [
    {
      id: 'inv-2026-009',
      invoiceNumber: 'INV-2026-0901',
      date: '2026-09-01',
      dueDate: '2026-09-15',
      planTier: 'professional',
      planName: 'Professional Plan (25 Seats)',
      billingInterval: 'monthly',
      seatsCount: 25,
      subtotal: 725.0,
      tax: 0.0,
      total: 725.0,
      currency: 'USD',
      status: 'paid',
      paymentMethodSummary: 'Visa ending in 4242',
      items: [
        {
          description: 'Professional Plan - Monthly Subscription (25 Team Seats)',
          qty: 25,
          unitPrice: 29.0,
          amount: 725.0,
        },
      ],
    },
    {
      id: 'inv-2026-008',
      invoiceNumber: 'INV-2026-0801',
      date: '2026-08-01',
      dueDate: '2026-08-15',
      planTier: 'professional',
      planName: 'Professional Plan (25 Seats)',
      billingInterval: 'monthly',
      seatsCount: 25,
      subtotal: 725.0,
      tax: 0.0,
      total: 725.0,
      currency: 'USD',
      status: 'paid',
      paymentMethodSummary: 'Visa ending in 4242',
      items: [
        {
          description: 'Professional Plan - Monthly Subscription (25 Team Seats)',
          qty: 25,
          unitPrice: 29.0,
          amount: 725.0,
        },
      ],
    },
    {
      id: 'inv-2026-007',
      invoiceNumber: 'INV-2026-0701',
      date: '2026-07-01',
      dueDate: '2026-07-15',
      planTier: 'professional',
      planName: 'Professional Plan (10 Seats)',
      billingInterval: 'monthly',
      seatsCount: 10,
      subtotal: 290.0,
      tax: 0.0,
      total: 290.0,
      currency: 'USD',
      status: 'paid',
      paymentMethodSummary: 'Mastercard ending in 8831',
      items: [
        {
          description: 'Professional Plan - Monthly Subscription (10 Team Seats)',
          qty: 10,
          unitPrice: 29.0,
          amount: 290.0,
        },
      ],
    },
  ],
};
